machine:
    node:
        version: 6.3.1
jobs:
   build:
     docker:
       - image: circleci/node:6.10.3
       - image: circleci/mongo:3.4.4
     steps:
       - checkout
       - run: npm install
       - run:
           name: Instantiate server_config.json
           command: 'mv server_config.json.example server_config.json'
       - run:
           name: Instantiate github-keys.json
           command: 'echo "{ \"clientID\": \"$GITHUB_CLIENT_ID\", \"clientSecret\": \"$GITHUB_CLIENT_SECRET\", \"callbackURL\": \"$GITHUB_CALLBACK_URL\"}">github-keys.json'
       - run:
           name: Run server in background
           command: 'npm start&'
       - run:
           name: Get PID of server
           command: 'SERVER_PID=$!'
       - run:
           name: Test server
           command: 'npm test'
       - run:
           name: Kill server
           command: 'kill $SERVER_PID'
          
       
