machine:
    node:
        version: 6.3.1
jobs:
   build:
     docker:
       - image: circleci/node:6.10.3
     steps:
       - checkout
       - run: npm install
       - run:
           name: Instantiate server_config.json
           command: 'mv server_config.json.example server_config.json'
       - run: npm start
       - run: npm test
       
